config/routes.rb
Rails.application.routes.draw do
    get 'dancers/isadancer'
    get 'igdancer/show'
    get 'notdancer/index'
    resources :dancers
    resources :igdancer
    resources :notdancer
    root to: 'dancers#show'
    get '/button', to: 'dancers#button'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dancer.rb
class Dancer < ApplicationRecord
end

app/models/igdancer.rb
class Igdancer < ApplicationRecord
end

app/models/notdancer.rb
class Notdancer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dancers_controller.rb
class DancersController < ApplicationController
 def index
    @dancers = Dancer.all
  end
  def new
    @dancer = Dancer.new
    respond_to do |format|
      format.html
      format.json
      end
      render :new
  end

  def create
   @dancer = Dancer.new(dancer_param)
    respond_to do |format|
       if @dancer.save
        format.html { redirect_to '/dancers/isadancer', notice: "Save process completed!" }
        format.json { render json: @dancer, status: :created, location: @dancer }
       else
          format.html {
            flash.now[:notice]="Save proccess coudn't be completed!"
            render :new
          }
          format.json { render json: @dancer.errors, status: :unprocessable_entity}
      end
    end
  end
def dancer_param
      params.require(:dancer).permit(:firstname, :lastname, :location, :dancestyle, :email, :phone, :ighandle)
    end

  def show
    @dancer = Dancer.all
  end

  def destroy
    @dancer = Dancer.find(dancerID)
    @dancer.destroy
    redirect_to '/dancers/show'
  end

  def button

  end

  def isadancer
    render :isadancer
  end
  private

    def dancerI
      params.require(:dancer).permit!
    end
    def dancerID
      params.require(:id)
    end

    def search
      if params[:search]
        @dancers = Dancer.search(params[:search]).order("created_at DESC")
      else
        @dancers = Dancer.all.order("created_at DESC")
      end
    end
end

app/controllers/igdancer_controller.rb
class IgdancerController < ApplicationController
  def index
     @igdancers = Igdancer.all
   end
   def new
     @igdancer = Igdancer.new
     respond_to do |format|
       format.html
       format.json
       end
       render :new
   end

   def create
    @igdancer = Igdancer.new(igdancer_param)
     respond_to do |format|
        if @igdancer.save
         format.html { redirect_to '/igdancer', notice: "Save process completed!" }
         format.json { render json:@igdancer, status: :created, location: @igdancer }
        else
           format.html {
             flash.now[:notice]="Save proccess coudn't be completed!"
             render :new
           }
           format.json { render json: @igdancer.errors, status: :unprocessable_entity}
       end
     end
   end
 def igdancer_param
       params.require(:igdancer).permit(:ighandle, :post, :followers, :following, :name, :bio)
     end

   def show
     @igdancer = Igdancer.all
   end

   def destroy
     @igdancer = Igdancer.find(igdancerID)
     @igdancer.destroy
     redirect_to '/igdancer/show'
   end
   private

     def igdancerI
       params.require(:igdancer).permit!
     end
     def igdancerID
       params.require(:id)
     end

     def search
       if params[:search]
         @igdancer = Igdancer.search(params[:search]).order("created_at DESC")
       else
         @igdancer = Igdancer.all.order("created_at DESC")
       end
     end
end

app/controllers/notdancer_controller.rb
class NotdancerController < ApplicationController
  def index
     @notdancers = Notdancer.all
   end
   def new
     @notdancer = Notdancer.new
     respond_to do |format|
       format.html
       format.json
       end
       render :new
   end

   def create
    @notdancer = Notdancer.new(notdancer_param)
     respond_to do |format|
        if @notdancer.save
         format.html { redirect_to '/dancers/isadancer', notice: "Save process completed!" }
         format.json { render json:@notdancer, status: :created, location: @notdancer }
        else
           format.html {
             flash.now[:notice]="Save proccess coudn't be completed!"
             render :new
           }
           format.json { render json: @notdancer.errors, status: :unprocessable_entity}
       end
     end
   end
 def notdancer_param
       params.require(:notdancer).permit(:ighandle)
     end

   def show
     @notdancer = Notdancer.all
   end

   def destroy
     @notdancer = Notdancer.find(notdancerID)
     @notdancer.destroy
     redirect_to '/notdancer/show'
   end
   private

     def notdancerI
       params.require(:notdancer).permit!
     end
     def notdancerID
       params.require(:id)
     end

     def search
       if params[:search]
         @notdancer = Notdancer.search(params[:search]).order("created_at DESC")
       else
         @notdancer = Notdancer.all.order("created_at DESC")
       end
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dancers_helper.rb
module DancersHelper
end

app/helpers/igdancer_helper.rb
module IgdancerHelper
end

app/helpers/notdancer_helper.rb
module NotdancerHelper
end

app/views/dancers/index.html.erb
<h1>Index Page</h1>
<div id="dancerig">
<%=
dancerC = Igdancer.all.map { |r| r.ighandle }
Dancer.where(ighandle: dancerC).delete_all
Dancer.where(ighandle: dancerC).ids
%>
</div>

<button type="button" name="TEST" onclick="trying()">TEST</button>
<br>
<input type="text" name="link" value="" id="linkId">

<p id="demo"></p>

app/views/dancers/isadancer.html.erb
<div id="dancerig">
<%= igs = Dancer.all.map { |r| r.ighandle  } %>
<%= dancerC = Dancer.all.map { |r| r.dancestyle } %>
<%= dancerIDelete = Igdancer.all.map { |r| r.ighandle }
Dancer.where(ighandle: dancerIDelete).delete_all %>
<%= dancerNDelete = Notdancer.all.map { |r| r.ighandle }
Dancer.where(ighandle: dancerNDelete).delete_all %>
</div>



<script>
    var igsData = <%= raw igs %>;

    function openInstagram() {
        var d = igsData[0];
        window.open(`http://instagram.com/web/friendships/${igsData[0]}/follow/`);
        console.log(d);
        return d; // give us back the item of where we are now
    }
    var a = openInstagram();

    $(document).ready(function () {
        $('nobtn').on('click', function () {
            $.ajax({
                url: '/dancers/' + this.parentElement.id,
                type: 'DELETE',
                success: function (r) {

                }
            });
        });
    });
    function yesbtn() {
    }
    function nobtn() {
    }
    $(document).ready(function () {
        $('#nobtn').click(function () {
            $.ajax({
                url: "/notdancer",
                data: {
                    notdancer: {
                        ighandle: a,
                    }
                },
                error: function (error) {
                    console.log(error);
                },
                success: function (data) {
                  window.location.href = '/dancers/isadancer';
                },
                type: 'POST'
            });
        });

        $('#yesbtn').click(function () {
            $.ajax({
                url: "/igdancer",
                data: {
                    igdancer: {
                        ighandle: a,
                        post: "",
                        followers: "",
                        following: "",
                        name: "",
                        bio: "",
                    }
                },
                error: function (error) {
                    console.log(error);
                },
                success: function (data) {
                  window.location.href = '/dancers/isadancer';
                },
                type: 'POST'
            });
        });
    })
    window.onload = function(){
      document.getElementById("dancerIghandle").innerHTML = a;
      if(!window.location.hash) {
        window.location = window.location + '#loaded';
        window.location.reload();
      }
    }
</script>

<div class="container" id="isContainer">
    <br>
    <div class="jumbotron">
        <h2 class="display-4" id="title">Dancer Or Not A Dancer?</h2>
        <h2 id="dancerIghandle"></h2>
        <br>
        <button type="button" class="btn" id="GObtn" onclick="openInstagram()">Go To Dancer Page</button>
        <br>
        <br>
        <div id="myButtons">
        <button type="button" class="btnYes" id="yesbtn" onclick="yesbtn()">Yes</button>
        <button type="button" class="btn" id="nobtn" onclick="nobtn()">No</button>
        </div>
    </div>
</div>

app/views/dancers/new.html.erb
<div id="new_form">
    <h1>New Dancer</h1>

        <%= form_for Dancer.new do |form| %>
                <p>
                <%= form.label :firstname, "Firstname:" %>
                <%= form.text_field :firstname %>
                </p>
                <p>
                <%= form.label :lastname, "Lastname:" %>
                <%= form.text_field :lastname %>
                </p>
                <p>
                <%= form.label :location, "Location:" %>
                <%= form.text_field :location %>
                </p>
                <p>
                <%= form.label :dancestyle, "Dancestyle:" %>
                <%= form.text_field :dancestyle %>
                </p>
                <p>
                <%= form.label :email, "Email:" %>
                <%= form.text_field :email %>
                </p>
                <p>
                <%= form.label :phone, "Phone number:" %>
                <%= form.text_field :phone %>
                </p>
                <p>
                <%= form.label :ighandle, "Ighandle:" %>
                <%= form.text_field :ighandle %>
                </p>
            </p> 
            <p class='buttons'>
                <%= form.submit "Submit" %>
            </p>  
        <% end %>
</div>

app/views/dancers/show.html.erb
<div id="dancerig">
<%= Dancer.where(dancestyle: 'notADancer').delete_all%>
</div>
<table id="show_dancerData">
        <thead>
            <tr>
                <th scope="col" id="Firstname">Firstname</th>
                <th scope="col" id="Lastname">Lastname</th>
                <th scope="col" id="Location">Location</th>
                <th scope="col" id="Email">Email</th>
                <th scope="col" id="Dance Style">Dance Style</th>
                <th scope="col" id="Phone Number">Phone Number</th>
                <th scope="col" id="Instagram name">Instagram name</th>
                <th scope="col" id="Delete Entry">Delete Entry</th>

            </tr>
        </thead>
    <%= Dancer.find_each do |dancer| %>

        <tbody>
            <tr id='<%= dancer.id %>'>
                <td><%= dancer.firstname %></td>
                <td><%= dancer.lastname %></td>
                <td><%= dancer.location %></td>
                <td><%= dancer.email %></td>
                <td><%= dancer.dancestyle %></td>
                <td><%= dancer.phone %></td>
                <td><%= dancer.ighandle %></td>
                <td><%= link_to 'Delete', dancer_path(dancer), method: :delete, data: { confirm: 'Are you sure?' }, :id => "Database_delete"%></td>
                </tr>
        </tbody>
    <% end %>
</table>

app/views/igdancer/index.html.erb
<h1>inex</h1>

app/views/igdancer/new.html.erb
<div id="new_form">
  <h1>New IG Dancer</h1>
<p>IgHandle:</p>
<input type="text" name="link" value="" id="ighandle">
<p>Post:</p>
<input type="text" name="link" value="" id="post">
<p>Followers:</p>
<input type="text" name="link" value="" id="followers">
<p>Following:</p>
<input type="text" name="link" value="" id="following">
<p>Name:</p>
<input type="text" name="link" value="" id="name">
<p>Bio:</p>
<input type="text" name="link" value="" id="bio">

<button type="button" class="btnYes" id="trybtn" onclick="testing()">Submit</button>
</div>

app/views/igdancer/show.html.erb
<table id="show_dancerData">
        <thead>
            <tr>
                <th scope="col" id="ighandle">ighandle</th>
                <th scope="col" id="post">post</th>
                <th scope="col" id="followers">followers</th>
                <th scope="col" id="following">following</th>
                <th scope="col" id="name">name</th>
                <th scope="col" id="bio">bio</th>
                <th scope="col" id="Delete Entry">Delete Entry</th>

            </tr>
        </thead>
        <br>
        <br>
    <%= Igdancer.find_each do |igdancer| %>

        <tbody>
            <tr id='<%= igdancer.id %>'>
                <td><%= igdancer.ighandle %></td>
                <td><%= igdancer.post %></td>
                <td><%= igdancer.followers %></td>
                <td><%= igdancer.following %></td>
                <td><%= igdancer.name %></td>
                <td><%= igdancer.bio %></td>
                <td><%= link_to 'Delete', igdancer_path(igdancer), method: :delete, data: { confirm: 'Are you sure?' }, :id => "Database_delete"%></td>
                </tr>
        </tbody>
    <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rmsdata</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="navigation">
    <div id="navigation_logo">
      <%= image_tag("rmslogo.png") %>
    </div>
    <div id="navigation_right">
      <th>
        <td><%= link_to 'NotDancers', "/notdancer/show",  :id => "navigation_text"%></td>
        <td><%= link_to 'IgDancers', "/igdancer/show",  :id => "navigation_text"%></td>
        <td><%= link_to 'Show', "/dancers/show",  :id => "navigation_text"%></td>
        <td><%= link_to 'New', new_dancer_url, :id => "navigation_text"%></td>
        <td><a href="/dancers/isadancer" id="navigation_text" onclick="areyouadancer()">Are you A Dancer</a></td>
      <th>
    </div>
  </div>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>

app/views/notdancer/index.html.erb
<h1>Index</h1>

app/views/notdancer/new.html.erb
<h1>NEW PAGE</h1>

app/views/notdancer/show.html.erb
<table id="show_dancerData">
        <thead>
            <tr>
                <th scope="col" id="ighandle">ighandle</th>
                <th scope="col" id="Delete Entry">Delete Entry</th>

            </tr>
        </thead>
        <br>
        <br>
    <%= Notdancer.find_each do |notdancer| %>

        <tbody>
            <tr id='<%= notdancer.id %>'>
                <td><%= notdancer.ighandle %></td>
                <td><%= link_to 'Delete', notdancer_path(notdancer), method: :delete, data: { confirm: 'Are you sure?' }, :id => "Database_delete"%></td>
                </tr>
        </tbody>
    <% end %>
</table>